import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import { Navbar } from "./Layout/navbar";
import { Footer } from "./Layout/footer";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
  weight: "300",
});

export const metadata: Metadata = {
  title: "TNT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className= {` ${raleway.variable} mx-56`} >
        <Navbar/>
        {children}
        <Footer/>
        </body>

    </html>
  );
}
